csv:
  base: ./lib/bs-csv/assets/
  path:
    alliance_badges: ./csv_logic/alliance_badges.csv
    alliance_roles: ./csv_logic/alliance_roles.csv
    area_effects: ./csv_logic/area_effects.csv
    bosses: ./csv_logic/bosses.csv
    campaign: ./csv_logic/campaign.csv
    cards: ./csv_logic/cards.csv
    characters: ./csv_logic/characters.csv
    globals: ./csv_logic/globals.csv
    items: ./csv_logic/items.csv
    locations: ./csv_logic/locations.csv
    maps: ./csv_logic/maps.csv
    player_thumbnails: ./csv_logic/player_thumbnails.csv
    projectiles: ./csv_logic/projectiles.csv
    pins: ./csv_logic/pins.csv
    regions: ./csv_logic/regions.csv
    resources: ./csv_logic/resources.csv
    skills: ./csv_logic/skills.csv
    skins: ./csv_logic/skins.csv
    texts: ./texts.csv
    tiles: ./csv_logic/tiles.csv

json:
  base: ./json/