csv:
  base: ./lib/bs-csv/assets/
  path:
    alliance_badges: ./csv_logic/alliance_badges.csv
    alliance_roles: ./csv_logic/alliance_roles.csv
    area_effects: ./csv_logic/area_effects.csv
    bosses: ./csv_logic/bosses.csv
    campaign: ./csv_logic/campaign.csv
    cards: ./csv_logic/cards.csv
    characters: ./csv_logic/characters.csv
    globals: ./csv_logic/globals.csv
    items: ./csv_logic/items.csv
    locations: ./csv_logic/locations.csv
    maps: ./csv_logic/maps.csv
    player_thumbnails: ./csv_logic/player_thumbnails.csv
    projectiles: ./csv_logic/projectiles.csv
    regions: ./csv_logic/regions.csv
    resources: ./csv_logic/resources.csv
    skills: ./csv_logic/skills.csv
    skins: ./csv_logic/skins.csv
    texts: ./csv_client/texts.csv
    tiles: ./csv_logic/tiles.csv

json:
  base: ./json/
  alliance_badges: ./alliance_badges.json
  alliance_roles: ./alliance_roles.json
  area_effects: ./area_effects.json
  bosses: ./bosses.json
  campaign: ./campaign.json
  cards: ./cards.json
  characters: ./characters.json
  globals: ./globals.json
  items: ./items.json
  locations: ./locations.json
  maps: ./maps.json
  player_thumbnails: ./player_thumbnails.json
  projectiles: ./projectiles.json
  regions: ./regions.json
  resources: ./resources.json
  skills: ./skills.json
  skins: ./skins.json
  tiles: ./tiles.json
